### ISSUE TITLE
Refresh button still not working in 2.7.0

### ISSUE THREAD

**Issue by JohanSF** [Burry/organizr-v2-plex-theme#13]
I have 2.7.0 installed via the marketplace, running the organizr docker container with :latest tag.

Clicking the refresh button on a card opens opens the info instead of refreshing the cover:
![image](https://user-images.githubusercontent.com/6782603/49325847-6c1c1e80-f549-11e8-8aee-afb35e5fd8ca.png)
![image](https://user-images.githubusercontent.com/6782603/49325849-75a58680-f549-11e8-86cd-d9c68f537d4e.png)

I am currently using "Organizr V2 On-top of Burry" from https://github.com/Archmonger/Blackberry-Flat, but the issue persists even with that turned off. I have also tried clearing cache in my browser and in CloudFlare.

**Comment by Burry** [comment]
[Fixed in 2.8.0](https://github.com/causefx/Organizr/pull/993)

**Comment by JohanSF** [comment]
Will test when update is available through the marketplace.

**Comment by JohanSF** [comment]
Confirmed that it now works :D thank you!
