### ISSUE TITLE
Clicking on the refresh cover button seems to be broken

### ISSUE THREAD

**Issue by goldenpipes** [Burry/organizr-v2-plex-theme#5]
https://youtu.be/yatofMzYHII

click on the refresh image button and it loads info for the item. weird.

**Comment by jigahertz** [comment]
Just waiting for the fix to be approved!
https://github.com/Burry/organizr-v2-plex-theme/pull/4

**Comment by Burry** [comment]
Merged @jigahertz's changes!

**Comment by jigahertz** [comment]
@gilbN I will look into it sometime this weekend. Sorry for the delay!

**Comment by goldenpipes** [comment]
Borked again :(

**Comment by jigahertz** [comment]
oops, wait, I think I finally reproduced the issue. Hunting down the fix right now

**Comment by jigahertz** [comment]
@gilbN ok, I think I figured it out. Burry hasn't merged our Plex.css files yet. If you grab mine and dump it in your css/themes folder in organizrV2 then that should fix the issue. (Be sure to back up your current Plex.css just in case!)

**Comment by goldenpipes** [comment]
its broken again it seems
