### ISSUE TITLE
Blue backgrounds show up on elements in the splash screen and home page

### ISSUE THREAD

**Issue by mattCameron09** [Burry/organizr-v2-plex-theme#9]
I am seeing blue backgrounds show up on the splash screen like this: ![splash](https://user-images.githubusercontent.com/42557315/44370552-84cb6180-a48f-11e8-9fbb-c33dab710aa2.png)

They also show up on some elements on the home screen, but activating `Alternate Homepage Titles` fixes that.

Thanks to some help in the discord, we determined that appending `'.bg-info{background-color: transparent !important;}' >> Plex.css` seemed to fix the issue on both splash and homepage

**Comment by Burry** [comment]
[Just pushed a fix](https://github.com/causefx/Organizr/pull/941). Sorry was on vacation for a while.
